-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 17:46:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CSC675WholeSale` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CSC675WholeSale` DEFAULT CHARACTER SET utf8 ;
USE `CSC675WholeSale` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT NOT NULL ,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Brand` ;

CREATE TABLE IF NOT EXISTS `Brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brand_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `manager_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`manager_id`),
  UNIQUE INDEX `Admins_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `person` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym_Staff`
-- -----------------------------------------------------


DROP TABLE IF EXISTS `Gym_Staff` ;

CREATE TABLE IF NOT EXISTS `Gym_Staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `Age` INT NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agressive_shoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agressive_shoes` ;

CREATE TABLE IF NOT EXISTS `Agressive_shoes` (
  `aggresive_id` INT NOT NULL AUTO_INCREMENT,
  `size` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aggresive_id`),
  UNIQUE INDEX `aggresive_id_UNIQUE` (`aggresive_id` ASC) ,
  UNIQUE INDEX `size_UNIQUE` (`size` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Moderate_Shoe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Moderate_Shoe` ;

CREATE TABLE IF NOT EXISTS `Moderate_Shoe` (
  `moderate_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `size` INT NOT NULL,
  PRIMARY KEY (`moderate_id`),
  UNIQUE INDEX `moderate_id_UNIQUE` (`moderate_id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `size_UNIQUE` (`size` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climbing_Shoe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Climbing_Shoe` ;

CREATE TABLE IF NOT EXISTS `Climbing_Shoe` (
  `shoe_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `size` INT NOT NULL,
  `gear_id` INT NULL,
  `moderate_shoes` INT NOT NULL,
  `aggresive_shoes` INT NOT NULL,
  PRIMARY KEY (`shoe_id`, `moderate_shoes`, `aggresive_shoes`),
  UNIQUE INDEX `size_UNIQUE` (`size` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `shoe_id_UNIQUE` (`shoe_id` ASC) ,
  INDEX `FK_Shoes_Moderate_idx` (`moderate_shoes` ASC) ,
  INDEX `FK_Shoes_Aggresive_idx` (`aggresive_shoes` ASC) ,
  CONSTRAINT `FK_Shoes_Aggresive`
    FOREIGN KEY (`aggresive_shoes`)
    REFERENCES `Agressive_shoes` (`aggresive_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Shoes_Moderate`
    FOREIGN KEY (`moderate_shoes`)
    REFERENCES `Moderate_Shoe` (`moderate_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Harness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Harness` ;

CREATE TABLE IF NOT EXISTS `Harness` (
  `harness_id` INT NOT NULL,
  `type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`harness_id`),
  UNIQUE INDEX `harness_id_UNIQUE` (`harness_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climbing_Gear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Climbing_Gear` ;

CREATE TABLE IF NOT EXISTS `Climbing_Gear` (
  `gear_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `FK_Gear_Shoe`
    FOREIGN KEY (`gear_id`)
    REFERENCES `Climbing_Shoe` (`shoe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Gear_Harness`
    FOREIGN KEY (`gear_id`)
    REFERENCES `Harness` (`harness_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gym` ;

CREATE TABLE IF NOT EXISTS `Gym` (
  `gym_id` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `packages` INT NULL,
  `gear_sold` INT NOT NULL,
  `climbing_gear` VARCHAR(45) NOT NULL,
  `Gear_orders` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`gym_id`, `place`),
  UNIQUE INDEX `place_UNIQUE` (`place` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `packages_UNIQUE` (`packages` ASC) )
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Director` ;

CREATE TABLE IF NOT EXISTS `Director` (
  `director_id` INT NOT NULL,
  `admin` INT NOT NULL,
  `age` INT NOT NULL,
  `staff_fk` INT NULL,
  PRIMARY KEY (`director_id`, `admin`),
  INDEX `Fk_director_Staff_idx` (`staff_fk` ASC) ,
  UNIQUE INDEX `age_UNIQUE` (`age` ASC) ,
  UNIQUE INDEX `director_id_UNIQUE` (`director_id` ASC) ,
  CONSTRAINT `FK_Director_admin`
    FOREIGN KEY (`admin`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Fk_director_Staff`
    FOREIGN KEY (`staff_fk`)
    REFERENCES `Gym_Staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Deliveries` ;

CREATE TABLE IF NOT EXISTS `Deliveries` (
  `deliveries_id` INT NOT NULL AUTO_INCREMENT,
  `packages` VARCHAR(45) NOT NULL,
  `drivers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deliveries_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manufacturer` ;

CREATE TABLE IF NOT EXISTS `Manufacturer` (
  `manufacturer_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `deliveries_fk` INT NULL,
  PRIMARY KEY (`manufacturer_id`),
  UNIQUE INDEX `manufacturer_id_UNIQUE` (`manufacturer_id` ASC) ,
  INDEX `FK_Manufacturer_Deliveries _idx` (`deliveries_fk` ASC) ,
  CONSTRAINT `FK_Manufacturer_Deliveries `
    FOREIGN KEY (`deliveries_fk`)
    REFERENCES `Deliveries` (`deliveries_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliverer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Deliverer` ;

CREATE TABLE IF NOT EXISTS `Deliverer` (
  `deliverer_id` INT NOT NULL,
  `driver` VARCHAR(45) NULL,
  `age` INT NULL,
  `manufature_id` INT NOT NULL,
  `gym_fk` INT NOT NULL,
  PRIMARY KEY (`deliverer_id`, `gym_fk`, `manufature_id`),
  UNIQUE INDEX `deliverer_id_UNIQUE` (`deliverer_id` ASC) ,
  UNIQUE INDEX `driver_UNIQUE` (`driver` ASC) ,
  UNIQUE INDEX `manufature_fk_UNIQUE` (`manufature_id` ASC) ,
  UNIQUE INDEX `gym_fk_UNIQUE` (`gym_fk` ASC) ,
  CONSTRAINT `fk_deliverer_Manufaturer`
    FOREIGN KEY (`manufature_id`)
    REFERENCES `Manufacturer` (`manufacturer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_deliverer_gym`
    FOREIGN KEY (`gym_fk`)
    REFERENCES `Gym` (`gym_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Representative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Representative` ;

CREATE TABLE IF NOT EXISTS `Representative` (
  `rep_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `age` INT NOT NULL,
  `brand_id` INT NULL,
  `gear_shown` VARCHAR(100) NOT NULL,
   `gear_at_gyms` INT NOT NULL,
  `gym_visited` VARCHAR(100) NOT NULL,
  UNIQUE INDEX `rep_id_UNIQUE` (`rep_id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  PRIMARY KEY (`rep_id`),
  INDEX `FK_Rep_Brand _idx` (`brand_id` ASC) ,
  CONSTRAINT `FK_Rep_Brand `
    FOREIGN KEY (`brand_id`)
    REFERENCES `Brand` (`brand_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Retail_Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Retail_Manager` ;

CREATE TABLE IF NOT EXISTS `Retail_Manager` (
  `retail_id` INT NOT NULL,
  `packages` INT NOT NULL,
  `Profits_Fk` INT NOT NULL,
  PRIMARY KEY (`retail_id`, `Profits_Fk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym_Profits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gym_Profits` ;

CREATE TABLE IF NOT EXISTS `Gym_Profits` (
  `profits_id` INT NOT NULL,
  `profit` INT NOT NULL,
  `earning` DATE NOT NULL,
  `Retail_fk` INT NULL,
  PRIMARY KEY (`profits_id`),
  UNIQUE INDEX `profits_id_UNIQUE` (`profits_id` ASC) ,
  UNIQUE INDEX `profit_UNIQUE` (`profit` ASC) ,
  UNIQUE INDEX `proce_UNIQUE` (`earning` ASC) ,
  INDEX `FK_Profit_Manager_idx` (`Retail_fk` ASC) ,
  CONSTRAINT `FK_Profit_Manager`
    FOREIGN KEY (`Retail_fk`)
    REFERENCES `Retail_Manager` (`retail_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rock_Climber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rock_Climber` ;

CREATE TABLE IF NOT EXISTS `Rock_Climber` (
  `climber_id` INT NOT NULL ,
  `name` VARCHAR(45) NOT NULL,
  `gear_bought` INT NOT NULL,
    PRIMARY KEY (`climber_id`),
  UNIQUE INDEX `climber_id_UNIQUE` (`climber_id` ASC) ,
  INDEX `FK_Climber_Gym_idx` (`climber_id` ASC) ,
  CONSTRAINT `FK_Climber_Gym`
    FOREIGN KEY (`climber_id`)
    REFERENCES `Gym` (`gym_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Gym_Frontdesk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gym_Frontdesk` ;

CREATE TABLE IF NOT EXISTS `Gym_Frontdesk` (
  `frontdesk_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `start_sales` DECIMAL(6,2) ,
  `mid_sales` DECIMAL(6,2) ,
  `end_sales` DECIMAL(6,2) ,
  PRIMARY KEY (`frontdesk_id`),
  UNIQUE INDEX `frontdesk_id_UNIQUE` (`frontdesk_id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  CONSTRAINT `FK_Frontdesk_Staff`
    FOREIGN KEY (`frontdesk_id`)
    REFERENCES `Gym_Staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker` ;

CREATE TABLE IF NOT EXISTS `worker` (
  `worker_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`worker_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  CONSTRAINT `FK_Worker_Manufacture`
    FOREIGN KEY (`worker_id`)
    REFERENCES `Manufacturer` (`manufacturer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Worker_Manager`
    FOREIGN KEY (`worker_id`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stores` ;

CREATE TABLE IF NOT EXISTS `Stores` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gear_sold` INT NOT NULL,
  `climbing_gear` VARCHAR(45) NOT NULL,
  `gear_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `BuyingGear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BuyingGear` ;

CREATE TABLE IF NOT EXISTS `BuyingGear` (
  `climber_id` INT NOT NULL,
  `Gear_id` INT NOT NULL,
  `buying_id` INT NOT NULL,
  PRIMARY KEY (`climber_id`, `buying_id`),
  UNIQUE INDEX `climber_id_UNIQUE` (`climber_id` ASC) ,
  UNIQUE INDEX `Gear_id_UNIQUE` (`Gear_id` ASC) ,
  CONSTRAINT `FK_Buying_Climber`
    FOREIGN KEY (`climber_id`)
    REFERENCES `Rock_Climber` (`climber_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Buying_Gear`
    FOREIGN KEY (`Gear_id`)
    REFERENCES `Climbing_Gear` (`gear_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoTO` ;

CREATE TABLE IF NOT EXISTS `GoTO` (
  `Store_id` INT NULL,
  `climber_id` INT NULL,
  `go_id` INT NOT NULL,
  PRIMARY KEY (`go_id`),
  CONSTRAINT `FK_GoTo_Store`
    FOREIGN KEY (`Store_id`)
    REFERENCES `Stores` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GoTo_Climber`
    FOREIGN KEY (`climber_id`)
    REFERENCES `Rock_Climber` (`climber_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sports_Harness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sports_Harness` ;

CREATE TABLE IF NOT EXISTS `Sports_Harness` (
  `Harness_id` INT NOT NULL,
  `Size` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`Harness_id`),
  UNIQUE INDEX `Size_UNIQUE` (`Size` ASC) ,
  UNIQUE INDEX `Sports Harnesscol_UNIQUE` (`name` ASC) ,
  CONSTRAINT `FK_Sports_Harness`
    FOREIGN KEY (`Harness_id`)
    REFERENCES `Harness` (`harness_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recieves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recieves` ;

CREATE TABLE IF NOT EXISTS `Recieves` (
  `gym_id` INT NOT NULL,
  `climbing_gear_id` INT NOT NULL,
  `recieves_id` INT NULL,
  PRIMARY KEY (`gym_id`, `climbing_gear_id`),
  INDEX `Fk_Recieves_ClimbingGear_idx` (`climbing_gear_id` ASC) ,
  CONSTRAINT `Fk_Recieving_gym`
    FOREIGN KEY (`gym_id`)
    REFERENCES `Gym` (`gym_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Recieves_ClimbingGear`
    FOREIGN KEY (`climbing_gear_id`)
    REFERENCES `Climbing_Gear` (`gear_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orders` ;

CREATE TABLE IF NOT EXISTS `Orders` (
  `manager_id` INT NULL,
  `gear_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  `current_oder` INT NOT NULL,
  `previous_order` INT NOT NULL,
  `new_orders` INT NOT NULL DEFAULT 0,
  UNIQUE INDEX `manager_id_UNIQUE` (`manager_id` ASC) ,
  INDEX `FK_Ordering_Gear_idx` (`gear_id` ASC) ,
  PRIMARY KEY (`orders_id`),
  CONSTRAINT `FK_Orders_Manager`
    FOREIGN KEY (`manager_id`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Ordering_Gear`
    FOREIGN KEY (`gear_id`)
    REFERENCES `Climbing_Gear` (`gear_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Shown`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shown` ;

CREATE TABLE IF NOT EXISTS `Shown` (
  `rep_id` INT NOT NULL,
  `gear_id` INT NOT NULL,
  `shown_id` INT NOT NULL,
  INDEX `FK_shows_gear_idx` (`gear_id` ASC) ,
  PRIMARY KEY (`shown_id`),
  CONSTRAINT `FK_shows_gear`
    FOREIGN KEY (`gear_id`)
    REFERENCES `Climbing_Gear` (`gear_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Shown_Rep`
    FOREIGN KEY (`rep_id`)
    REFERENCES `Representative` (`rep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Talks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Talks` ;

CREATE TABLE IF NOT EXISTS `Talks` (
  `manager_id` INT NOT NULL,
  `rep_id` INT NOT NULL,
  `talk_id` INT NOT NULL,
  INDEX `FK_Talks_Rep_idx` (`rep_id` ASC) ,
  PRIMARY KEY (`manager_id`, `rep_id`, `talk_id`),
  CONSTRAINT `FK_talks_Manager`
    FOREIGN KEY (`manager_id`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Talks_Rep`
    FOREIGN KEY (`rep_id`)
    REFERENCES `Representative` (`rep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Profits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Profits` ;

CREATE TABLE IF NOT EXISTS `Profits` (
  `profit_id` INT NULL,
  `gym_id` INT NULL,
  `profits_id` INT NOT NULL,
  INDEX `FK_Associative_profit_idx` (`profit_id` ASC) ,
  PRIMARY KEY (`profits_id`),
  CONSTRAINT `FK_Profits_gym`
    FOREIGN KEY (`gym_id`)
    REFERENCES `Gym` (`gym_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL,
  CONSTRAINT `FK_Profits_profit`
    FOREIGN KEY (`profit_id`)
    REFERENCES `Gym_Profits` (`profits_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Account` ;

CREATE TABLE IF NOT EXISTS `Sales_Account` (
  `sales_id` INT NOT NULL,
  `accounts` VARCHAR(45) NULL,
  `brand_Fk` INT NULL,
  `user_Fk` INT NULL,
   `climber` INT NOT NULL ,
   `sales` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  
  PRIMARY KEY (`sales_id`),
  UNIQUE INDEX `brand_FK_UNIQUE` (`accounts` ASC) ,
  CONSTRAINT `FK_Sales_Brand`
    FOREIGN KEY (`brand_Fk`)
    REFERENCES `Brand` (`brand_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Fk_Sales_user`
    FOREIGN KEY (`user_Fk`)
    REFERENCES `User` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checking` ;

CREATE TABLE IF NOT EXISTS `checking` (
  `manager_id` INT NOT NULL,
  `sales_id` INT NOT NULL,
  `check_id` INT NOT NULL,
  UNIQUE INDEX `manager_id_UNIQUE` (`manager_id` ASC) ,
  UNIQUE INDEX `sales_id_UNIQUE` (`sales_id` ASC) ,
  PRIMARY KEY (`sales_id`, `manager_id`, `check_id`),
  CONSTRAINT `FK_check_manager`
    FOREIGN KEY (`manager_id`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Check_sales`
    FOREIGN KEY (`sales_id`)
    REFERENCES `Sales_Account` (`sales_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Receiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receiver` ;

CREATE TABLE IF NOT EXISTS `Receiver` (
  `Retail_fk` INT NOT NULL,
  `Deliveries_Fk` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  PRIMARY KEY (`Retail_fk`, `Deliveries_Fk`, `receiver_id`),
  UNIQUE INDEX `Retail_fk_UNIQUE` (`Retail_fk` ASC) ,
  CONSTRAINT `FK_Receiver_Deliveries`
    FOREIGN KEY (`Deliveries_Fk`)
    REFERENCES `Deliveries` (`deliveries_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Receiver_Retail`
    FOREIGN KEY (`Retail_fk`)
    REFERENCES `Retail_Manager` (`retail_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inventory` ;

CREATE TABLE IF NOT EXISTS `Inventory` (
  `inventory_id` INT NOT NULL,
  `items` VARCHAR(45) NULL,
  `count` INT NULL,
  `admin_Fk` INT NOT NULL,
  `Frontdesk_Fk` INT NOT NULL,
  `new_count` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`inventory_id`, `admin_Fk`, `Frontdesk_Fk`),
  UNIQUE INDEX `items_UNIQUE` (`items` ASC) ,
  UNIQUE INDEX `count_UNIQUE` (`count` ASC) ,
  UNIQUE INDEX `admin_Fk_UNIQUE` (`admin_Fk` ASC) ,
  CONSTRAINT `Fk_Inventory_Admin`
    FOREIGN KEY (`admin_Fk`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Invoice` ;

CREATE TABLE IF NOT EXISTS `Invoice` (
  `user_fk` INT NOT NULL,
  `admin_fk` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  PRIMARY KEY (`user_fk`, `admin_fk`, `invoice_id`),
  UNIQUE INDEX `user_fk_UNIQUE` (`user_fk` ASC) ,
  UNIQUE INDEX `Invoicecol_UNIQUE` (`invoice_id` ASC) ,
  UNIQUE INDEX `admin_fk_UNIQUE` (`admin_fk` ASC) ,
  CONSTRAINT `Fk_Invoice_User`
    FOREIGN KEY (`user_fk`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Invoice_Admin`
    FOREIGN KEY (`admin_fk`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locations` ;

CREATE TABLE IF NOT EXISTS `Locations` (
  `location_id` INT NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `staff_fk` INT NOT NULL,
  `gym_fk` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`location_id`, `gym_fk`, `staff_fk`),
  INDEX `FK_location_gym_idx` (`place` ASC) ,
  INDEX `FK_location_Staff_idx` (`staff_fk` ASC) ,
  CONSTRAINT `FK_location_gym`
    FOREIGN KEY (`place`)
    REFERENCES `Gym` (`place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_location_Staff`
    FOREIGN KEY (`staff_fk`)
    REFERENCES `Gym_Staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checks` ;

CREATE TABLE IF NOT EXISTS `checks` (
  `inventory_id` INT NOT NULL,
  `Frontdesk_id` INT NOT NULL,
  `checks_id` INT NOT NULL,
  PRIMARY KEY (`inventory_id`, `Frontdesk_id`, `checks_id`),
  INDEX `FK_Check_Frontdesk_idx` (`Frontdesk_id` ASC) ,
  CONSTRAINT `FK_Check_Inventory`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `Inventory` (`inventory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Check_Frontdesk`
    FOREIGN KEY (`Frontdesk_id`)
    REFERENCES `Gym_Frontdesk` (`frontdesk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sale_PerDay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sale_PerDay` ;

CREATE TABLE IF NOT EXISTS `Sale_PerDay` (
  `sales_id` INT NOT NULL,
  `previous_sales` DECIMAL(6,2) NOT NULL,
  `current_sales` DECIMAL(6,2) NOT NULL,
  `gym_sales` INT NOT NULL,
  `gym_name` VARCHAR(45) NOT NULL,
  `mon` DECIMAL(6,2) NOT NULL,
  `tue` DECIMAL(6,2) NOT NULL,
  `wed` DECIMAL(6,2) NOT NULL,
  `thur` DECIMAL(6,2) NOT NULL,
  `fri` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`sales_id`),
  INDEX `FK_Sale_Gym_idx` (`gym_sales` ASC) ,
  CONSTRAINT `FK_Sale_Gym`
    FOREIGN KEY (`gym_sales`)
    REFERENCES `Gym` (`gym_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `climber_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climber_purchase` ;

CREATE TABLE IF NOT EXISTS `climber_purchase` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `climber` INT  NULL,
  `climbers_purchases` DECIMAL(6,2) NULL DEFAULT 0.00,
  PRIMARY KEY (`purchase_id`),
  INDEX `FK_Purchase_Climber_idx` (`climber` ASC) ,
  CONSTRAINT `FK_Purchase_Climber`
    FOREIGN KEY (`climber`)
    REFERENCES `Rock_Climber` (`climber_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `members_sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `members_sales` ;

CREATE TABLE IF NOT EXISTS `members_sales` (
  `sales_id` INT NOT NULL AUTO_INCREMENT,
  `climber` INT  NULL ,
  `total_purchase` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `items_bought` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`sales_id`),
  INDEX `FK_Memberr_climber_idx` (`climber` ASC) ,
  CONSTRAINT `FK_Member_Sales`
    FOREIGN KEY (`sales_id`)
    REFERENCES `Sales_Account` (`sales_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Memberr_climber`
    FOREIGN KEY (`climber`)
    REFERENCES `Rock_Climber` (`climber_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Stores_sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stores_sales` ;

CREATE TABLE IF NOT EXISTS `Stores_sales` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `climber` INT  NULL,
  `total_purchase` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `items_bought` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`store_id`),
  INDEX `FK_Store_Climbers_idx` (`climber` ASC) ,
  CONSTRAINT `FK_Store_Climbers`
    FOREIGN KEY (`climber`)
    REFERENCES `Rock_Climber` (`climber_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Store_Store`
    FOREIGN KEY (`store_id`)
    REFERENCES `Stores` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
